name: Build iOS Archive

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter with cache
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.5'
          cache: true

      - name: Verify Flutter installation
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Create iOS platform if missing
        run: flutter create --platforms=ios .

      - name: Build iOS archive
        run: flutter build ipa --no-codesign

      - name: Upload archive artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-archive
          path: build/ios/archive/Runner.xcarchive